### ISSUE TITLE
[Question] Why is this deprecated?

### ISSUE THREAD

**Issue by julealgon** [rebus-org/Rebus.StructureMap#3]
See title. Would be nice to have an update in the readme to indicate why exactly this repository is considered deprecated.

**Comment by mookid8000** [comment]
I was under the impression that StructureMap was not being maintained anymore.

In addition to this, I seem to recall that SM had severe difficulties in resolving polymorphically compatible handlers (i.e. observing contravariance).

Is this something you know anything about?

**Comment by julealgon** [comment]
> I was under the impression that StructureMap was not being maintained anymore.

You seem to be correct.
https://github.com/structuremap/structuremap
![image](https://user-images.githubusercontent.com/461579/130144416-2029b151-8e2b-4154-aec3-83b359b05348.png)

https://jeremydmiller.com/2018/01/29/sunsetting-structuremap/

I was not aware of that and thought it was something on this project itself that caused it to be marked obsolete. Thanks for bringing that to my attention.
