### ISSUE TITLE
The package does not work with rebus 7.0.0

### ISSUE THREAD

**Issue by Hassan1984** [rebus-org/Rebus.StructureMap#4]
In rebus version 7.0.0 the `transactionContext.OnDisposed` now takes `Action<ITransactionContext> disposedAction` as param thats why the `GetHandlers` method in `StructureMapContainerAdapter.cs` throws `Could not 'GetOrAdd' item with key 'nested-structuremap-container' as type StructureMap.IContainer ---> System.MissingMethodException`.

I know that this package has been deprecated but it could still be nice to support the latest rebus version as the error is not related to structuremap it self. 

I will love to create a PR for fixing the issue.

**Comment by mookid8000** [comment]
Hi @Hassan1984 , sorry but Rebus.StructureMap is no longer maintained. StructureMap hasn't had new versions released since 2019, so I would recommend that look around for an alternative.

Have you tried Microsoft's DI container ("Microsoft.Extensions.DependencyInjection")?
